version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app-network

  api:
    build: .
    working_dir: /app/apps/api
    command: sh -c "../../wait-for-it.sh postgres:5432 -- pnpm start"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_COOKIE_NAME: ${JWT_COOKIE_NAME}
      JWT_TTL_SECS: ${JWT_TTL_SECS}
      REFRESH_JWT_COOKIE_NAME: ${REFRESH_JWT_COOKIE_NAME}
      REFRESH_JWT_TTL_SECS: ${REFRESH_JWT_TTL_SECS}
      REDIS_HOST: redis
      REDIS_DB: ${REDIS_DB}
      PAGINATION_LIMIT: ${PAGINATION_LIMIT}
      PAGINATION_LIMIT_MAX: ${PAGINATION_LIMIT_MAX}
      NODE_ENV: ${NODE_ENV}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_INITIALIZE_TABLES: ${POSTGRES_INITIALIZE_TABLES}
      POSTGRES_CLIENT_MIN_MESSAGES: ${POSTGRES_CLIENT_MIN_MESSAGES}
      POSTGRES_SEED_DB: ${POSTGRES_SEED_DB}
      POSTGRES_SEED_ROWS: ${POSTGRES_SEED_ROWS}
    ports:
      - '5001:5001'
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  stockbase:
    build: .
    working_dir: /app/apps/stockbase
    command: sh -c "pnpm start"
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - '3000:3000'
    networks:
      - app-network

  worker:
    build: .
    working_dir: /app/apps/worker
    command: sh -c "cd /app/packages/db; pnpm run migrate:up && cd /app/apps/worker; ../../wait-for-it.sh postgres:5432 -- pnpm start"
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_INITIALIZE_TABLES: ${POSTGRES_INITIALIZE_TABLES}
      POSTGRES_CLIENT_MIN_MESSAGES: ${POSTGRES_CLIENT_MIN_MESSAGES}
      POSTGRES_SEED_DB: ${POSTGRES_SEED_DB}
      POSTGRES_SEED_ROWS: ${POSTGRES_SEED_ROWS}
    depends_on:
      - postgres
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - stockbase
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
